import {validateQuiz,localized,MAX_QUIZ_BYTES} from '../server/schema.js';
const ui=window.MuseumI18n,t=x=>ui.t(x);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let data;
let message='';const notice=x=>{message=x;document.querySelector('#status').textContent=t(x);};
function preview(){if(!data)return;const quiz=data.quiz,lang=ui.language;document.querySelector('#preview').innerHTML=`<h2>${esc(localized(quiz.title,lang))} · ${quiz.questions.length}</h2>${quiz.questions.map((q,i)=>`<article><h3>${i+1}. ${esc(localized(q.prompt,lang))} · ${esc(t('Level'))} ${q.difficulty||esc(t('unclassified'))}</h3>${q.image?`<img src="${esc(q.image)}" alt="">`:''}<ol type="A">${q.answers.map((a,j)=>`<li ${j===q.correct?'class="good"':''}>${esc(localized(a,lang))}${j===q.correct?' ✓':''}</li>`).join('')}</ol><p>${esc(localized(q.explanation,lang))}</p></article>`).join('')}`;}
async function parse(){const raw=document.querySelector('#payload').value;if(new TextEncoder().encode(raw).length>MAX_QUIZ_BYTES)throw Error('The file exceeds 10 MB.');let input;try{input=JSON.parse(raw.trim().replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''));}catch{throw Error('Invalid JSON. Upload the complete JSON file produced by your assistant.');}const quiz=validateQuiz(input.quiz||input);data={...input,quiz};preview();notice('Format checked. Review the questions and correct answers before submitting.');}
document.querySelector('#file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;document.querySelector('#file-name').textContent=file.name;if(file.size>MAX_QUIZ_BYTES)throw Error('File too large.');document.querySelector('#payload').value=await file.text();await parse();}catch(e){notice(e.message);}};
document.querySelector('#check').onclick=()=>parse().catch(e=>notice(e.message));
document.querySelector('#copy').onclick=async()=>{try{const response=await fetch('/quiz-prompt.txt');if(!response.ok)throw Error('Unable to load the prompt. Please try again.');const text=({en:'Please communicate with me in English.',fr:'Merci de communiquer avec moi en français.',tl:'Mangyaring makipag-usap sa akin sa Tagalog.'}[ui.language])+'\n\n'+await response.text();try{await navigator.clipboard.writeText(text);notice('Prompt copied: add your instructions at the end in your AI assistant.');}catch{const field=document.querySelector('#prompt');field.hidden=false;field.value=text;field.select();notice('Copy the selected text.');}}catch{notice('Unable to load the prompt. Please try again.');}};
let receipt;
function showReceipt(){if(!receipt)return;const link=document.createElement('a');link.href='https://retro-museum.net/?lang='+ui.language+'#report='+encodeURIComponent(receipt.id);link.textContent=t('Follow the review');document.querySelector('#status').replaceChildren(document.createTextNode(t('Submission received')+' · '+receipt.id+' · '),link);}
document.querySelector('#submit').onclick=async e=>{e.target.disabled=true;try{await parse();if(!document.querySelector('#rights').checked)throw Error('Confirm publication rights.');if(!data.publication)throw Error('The JSON must include publication, as specified in the prompt.');const response=await fetch('https://retro-museum.net/api/quizzes/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Submission failed.');receipt=result;message='';showReceipt();}catch(e){notice(e.message);}finally{e.target.disabled=false;}};
document.addEventListener('museum-language-change',()=>{preview();if(message)notice(message);else showReceipt();});
