import {localized} from '../server/schema.js';
let state,role='display',online=false,choice=null,lastQuestion='',lastRender='',audio,muted=false,lastCue='',serial=0;
const words={en:{title:'THE MILLION QUIZ',waiting:'Your next great answer.',lobby:'Scan the QR to join. The organiser chooses a quiz and starts the show.',question:'Question',locked:'Answer locked',confirm:'Final answer',choose:'Choose your answer',correct:'Correct answer',practice:'Practice round · your prize is secured',spectator:'You join at the next question',finished:'What a performance!',ranking:'Leaderboard',team:'Team prize',fifty:'50 : 50',pause:'The show is paused',answers:'answers locked',again:'Play again',point:'points',sound:'Sound',ready:'Get ready',elimination:'Prize ladder',cooperative:'Together to a million',rankingMode:'Everyone stays in the game',tie:'Ties share the same result. Team votes need a unique majority.'},fr:{title:'LE QUIZ MILLION',waiting:'À vous de briller.',lobby:'Scannez le QR pour rejoindre. La régie choisit le quiz et lance le jeu.',question:'Question',locked:'Réponse enregistrée',confirm:'C’est mon dernier mot',choose:'Choisissez votre réponse',correct:'Bonne réponse',practice:'Entraînement · votre gain est assuré',spectator:'Vous jouerez à la prochaine question',finished:'Quelle performance !',ranking:'Classement',team:'Gain de l’équipe',fifty:'50 : 50',pause:'Le jeu est en pause',answers:'réponses enregistrées',again:'Rejouer',point:'points',sound:'Son',ready:'Préparez-vous',elimination:'L’échelle des gains',cooperative:'Ensemble vers le million',rankingMode:'Tout le monde reste en jeu',tie:'Les ex æquo partagent le même résultat. Le vote collectif exige une majorité unique.'},tl:{title:'MILYONG QUIZ',waiting:'Oras mong magningning.',lobby:'I-scan ang QR para sumali. Pipili ng quiz at magsisimula ang tagapag-ayos.',question:'Tanong',locked:'Naitala ang sagot',confirm:'Pinal na sagot',choose:'Piliin ang iyong sagot',correct:'Tamang sagot',practice:'Pagsasanay · ligtas ang iyong premyo',spectator:'Sasali ka sa susunod na tanong',finished:'Ang galing ninyo!',ranking:'Ranggo',team:'Premyo ng koponan',fifty:'50 : 50',pause:'Naka-pause ang laro',answers:'naitalang sagot',again:'Maglaro muli',point:'puntos',sound:'Tunog',ready:'Humanda',elimination:'Hagdan ng premyo',cooperative:'Sama-sama tungo sa milyon',rankingMode:'Lahat ay patuloy na naglalaro',tie:'Magkapantay ang tabla. Kailangan ng natatanging may pinakamaraming boto.'}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=k=>(words[state?.language]||words.en)[k]||k;
const number=n=>Math.round(n||0).toLocaleString('en-US');
const send=(action,value)=>parent.postMessage({retroMuseum:1,type:'action',id:'quiz-'+Date.now()+'-'+(++serial),action,value},'*');
function tone(kind){if(muted||!audio||audio.state!=='running')return;const melody=kind==='finished'?[523,659,784,1046]:kind==='reveal'?[392,523,659]:[330,440];melody.forEach((frequency,i)=>{const o=audio.createOscillator(),g=audio.createGain(),at=audio.currentTime+i*.13;o.type='sine';o.frequency.value=frequency;g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.065,at+.015);g.gain.exponentialRampToValueAtTime(.001,at+.3);o.connect(g);g.connect(audio.destination);o.start(at);o.stop(at+.31);});}
function render(){
 const party=state?.party,q=party?.community;document.documentElement.lang=state?.language||'en';
 const key=party?.id+':'+q?.index;if(key!==lastQuestion){choice=null;lastQuestion=key;}
 const cue=party?.id+':'+state?.phase+':'+q?.revision;if(cue!==lastCue){tone(q?.stage||state?.phase);lastCue=cue;}
 const fingerprint=JSON.stringify([role,online,state?.language,state?.phase,party?.id,party?.players,q,choice,muted]);if(fingerprint===lastRender)return;lastRender=fingerprint;
 const profile=id=>party?.players.find(p=>p.id===id),name=id=>profile(id)?.name||'Player '+(profile(id)?.number||'');
 const ranking=q?`<section class="ranking"><h2>${t(q.mode==='cooperative'?'team':'ranking')}</h2>${q.mode==='cooperative'?`<strong class="big-gain">${number(q.team.gain)}</strong>`:q.ranking.map((p,i)=>`<div class="rank ${p.id===party.you?'mine':''}"><span>${i&&q.ranking[i-1].gain===p.gain&&q.ranking[i-1].score===p.score?'=':i+1}</span><b>${esc(name(p.id))}</b><strong>${number(p.gain)}</strong><small>${p.score} ${t('point')}</small></div>`).join('')}</section>`:'';
 const me=q?.you,can=online&&role==='controller'&&state.phase==='playing'&&q?.stage==='question'&&me&&!me.spectator&&me.answer===null;
 const question=q?`<div class="question-meta"><span>${t('question')} ${q.index+1} / ${q.total}</span><strong>${number(q.gain)}</strong><span class="clock" aria-label="seconds">${q.left}s</span></div><div class="question-text">${esc(localized(q.question.prompt,state.language))}</div>${q.question.image?`<img class="question-image" src="${esc(q.question.image)}" alt="${t('question')} ${q.index+1}">`:''}<div class="answers">${q.question.answers.map((a,i)=>`<button type="button" data-answer="${i}" class="answer ${choice===i||me?.answer===i?'chosen':''} ${q.stage!=='question'&&q.question.correct===i?'correct':''} ${me?.hidden.includes(i)?'removed':''}" ${!can||me?.hidden.includes(i)?'disabled':''}><b>${'ABCD'[i]}</b><span>${esc(localized(a,state.language))}</span></button>`).join('')}</div>${role==='controller'&&q.stage==='question'?`<div class="controls"><button class="fifty" data-fifty ${!can||me.used?'disabled':''}>${t('fifty')}</button><button class="final" data-confirm ${!can||choice===null?'disabled':''}>${me?.answer!==null&&me?t('locked'):t('confirm')}</button></div><p class="hint">${me?.spectator?t('spectator'):me&&!me.alive&&q.mode!=='ranking'?t('practice'):t('choose')}</p>`:''}${q.stage!=='question'?`<p class="explanation">${t('correct')} : ${'ABCD'[q.question.correct]} · ${esc(localized(q.question.explanation,state.language))}</p>`:`<p class="hint">${q.answered} / ${q.participantCount} ${t('answers')}</p>`}`:'';
 document.querySelector('#app').innerHTML=`<main class="show ${role}"><div class="spotlights" aria-hidden="true"></div><header><div class="wordmark">RETRO_MUSEUM <small>${t('title')}</small></div><button class="sound" data-sound aria-label="${t('sound')}">${muted?'♪ ×':'♪'}</button></header>${!q?`<section class="lobby"><div class="emblem">?</div><p class="eyebrow">1 → 1,000,000</p><h1>${t('waiting')}</h1><p>${t('lobby')}</p><strong>${party?.players.filter(p=>p.connected).length||0} players</strong></section>`:`<div class="show-heading"><h1>${esc(localized(q.title,state.language))}</h1><p>${t(q.mode==='ranking'?'rankingMode':q.mode)}</p></div><div class="play-grid"><section class="question-card" aria-live="polite">${question}</section>${role==='display'||q.ended?ranking:`<aside class="personal-gain"><span>${esc(name(party.you))}</span><strong>${number(q.mode==='cooperative'?q.team.gain:me?.gain)}</strong></aside>`}</div>`}${state?.phase==='paused'||state?.phase==='intro'?`<div class="overlay"><div class="emblem">${state.phase==='intro'?Math.max(1,Math.ceil(state.introRemainingMs/1000)):'Ⅱ'}</div><h2>${t(state.phase==='intro'?'ready':'pause')}</h2></div>`:''}${(q?.ended||state?.phase==='ended')?`<div class="ending"><h2>${t('finished')}</h2><p>${t('tie')}</p>${role==='controller'?`<button class="final" data-replay>${t('again')}</button>`:''}<div class="confetti" aria-hidden="true">✦ · ✧ · ✦ · ✧ · ✦</div></div>`:''}</main>`;
}
document.addEventListener('click',async e=>{
 const button=e.target.closest('button');if(!button||button.disabled)return;
 if(!audio){const Context=window.AudioContext||window.webkitAudioContext;if(Context)audio=new Context();}if(audio?.state==='suspended')await audio.resume().catch(()=>{});
 if(button.hasAttribute('data-sound')){muted=!muted;render();return;}
 if(button.dataset.answer!==undefined){choice=Number(button.dataset.answer);render();return;}
 if(button.hasAttribute('data-confirm')){send('quizAnswer',{question:state.party.community.index,answer:choice});tone('locked');}
 if(button.hasAttribute('data-fifty'))send('quizFifty',{question:state.party.community.index});
 if(button.hasAttribute('data-replay'))send('playAgain');
});
addEventListener('message',e=>{if(e.source!==parent||e.data?.retroMuseum!==1)return;const m=e.data;if(m.type==='suspend'){choice=null;return;}if(m.type==='state'){state=m.state;role=m.role;online=m.online;try{render();}finally{parent.postMessage({retroMuseum:1,type:'rendered',renderId:m.renderId},'*');}}if(m.type==='error'){document.querySelector('.hint')?.replaceChildren(document.createTextNode(m.message||'Please try again.'));}});
parent.postMessage({retroMuseum:1,type:'ready',renderAck:true},'*');
