import {celebration} from './celebration.js';
import {quizCue,quizWinners,quizWon,playQuizCue} from '../public/quiz-audio.js';
import {patchView} from './patch-view.js';
import {localized} from '../server/schema.js';
let state,role='display',online=false,choice=null,lastQuestion='',lastRender='',audio,muted=false,lastCue='',serial=0,previousQuiz,hostAudio=false,stopAudio=()=>{};
const words={en:{perCorrect:'per correct answer',title:'THE MILLION QUIZ',waiting:'Your next great answer.',lobby:'Scan the QR to join. The organiser chooses a quiz and starts the show.',question:'Question',locked:'Answer locked',confirm:'Final answer',choose:'Choose your answer',correct:'Correct answer',practice:'Practice round · your prize is secured',spectator:'You join at the next question',finished:'What a performance!',ranking:'Leaderboard',team:'Team prize',fifty:'50 : 50',pause:'The show is paused',answers:'answers locked',again:'Play again',point:'points',sound:'Sound',ready:'Get ready',elimination:'Prize ladder',cooperative:'Together to a million',rankingMode:'Everyone stays in the game',tie:'Ties share the same result. Team votes need a unique majority.'},fr:{perCorrect:'par bonne réponse',title:'LE QUIZ MILLION',waiting:'À vous de briller.',lobby:'Scannez le QR pour rejoindre. La régie choisit le quiz et lance le jeu.',question:'Question',locked:'Réponse enregistrée',confirm:'C’est mon dernier mot',choose:'Choisissez votre réponse',correct:'Bonne réponse',practice:'Entraînement · votre gain est assuré',spectator:'Vous jouerez à la prochaine question',finished:'Quelle performance !',ranking:'Classement',team:'Gain de l’équipe',fifty:'50 : 50',pause:'Le jeu est en pause',answers:'réponses enregistrées',again:'Rejouer',point:'points',sound:'Son',ready:'Préparez-vous',elimination:'L’échelle des gains',cooperative:'Ensemble vers le million',rankingMode:'Tout le monde reste en jeu',tie:'Les ex æquo partagent le même résultat. Le vote collectif exige une majorité unique.'},tl:{perCorrect:'bawat tamang sagot',title:'MILYONG QUIZ',waiting:'Oras mong magningning.',lobby:'I-scan ang QR para sumali. Pipili ng quiz at magsisimula ang tagapag-ayos.',question:'Tanong',locked:'Naitala ang sagot',confirm:'Pinal na sagot',choose:'Piliin ang iyong sagot',correct:'Tamang sagot',practice:'Pagsasanay · ligtas ang iyong premyo',spectator:'Sasali ka sa susunod na tanong',finished:'Ang galing ninyo!',ranking:'Ranggo',team:'Premyo ng koponan',fifty:'50 : 50',pause:'Naka-pause ang laro',answers:'naitalang sagot',again:'Maglaro muli',point:'puntos',sound:'Tunog',ready:'Humanda',elimination:'Hagdan ng premyo',cooperative:'Sama-sama tungo sa milyon',rankingMode:'Lahat ay patuloy na naglalaro',tie:'Magkapantay ang tabla. Kailangan ng natatanging may pinakamaraming boto.'}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const extra={en:{winner:'Winner',winners:'Winners',teamWon:'Team victory!',yourWin:'You won!',bravo:'Well played!',next:'The next question is coming…',wrong:'Keep going!',lockedCue:'Your answer is locked in'},fr:{winner:'Gagnant',winners:'Gagnants',teamWon:'Victoire de l’équipe !',yourWin:'Vous avez gagné !',bravo:'Bravo !',next:'La prochaine question arrive…',wrong:'On continue !',lockedCue:'Votre réponse est enregistrée'},tl:{winner:'Panalo',winners:'Mga panalo',teamWon:'Panalo ang koponan!',yourWin:'Panalo ka!',bravo:'Magaling!',next:'Parating na ang susunod na tanong…',wrong:'Tuloy lang!',lockedCue:'Naitala na ang sagot mo'}};
const t=k=>(words[state?.language]||words.en)[k]||(extra[state?.language]||extra.en)[k]||k;
const number=n=>Math.round(n||0).toLocaleString('en-US');
const send=(action,value)=>parent.postMessage({retroMuseum:1,type:'action',id:'quiz-'+Date.now()+'-'+(++serial),action,value},'*');
function tone(kind){if(hostAudio||muted)return;stopAudio();stopAudio=playQuizCue(audio,kind);}

function render(){
 const party=state?.party,q=party?.community;document.documentElement.lang=state?.language||'en';
 const key=party?.id+':'+q?.index;if(key!==lastQuestion){choice=null;lastQuestion=key;}
 const cue=party?.id+':'+q?.index+':'+q?.stage;if(cue!==lastCue){if(previousQuiz?.party===party?.id){const sound=quizCue(previousQuiz.q,q,role,party?.you);if(sound)tone(sound);}lastCue=cue;}previousQuiz={party:party?.id,q};
 const fingerprint=JSON.stringify([role,online,state?.language,state?.phase,party?.id,party?.players,q,choice,muted,hostAudio,state?.phase==='intro'?Math.ceil(state.introRemainingMs/1000):null]);if(fingerprint===lastRender)return;lastRender=fingerprint;
 const profile=id=>party?.players.find(p=>p.id===id),name=id=>profile(id)?.name||'Player '+(profile(id)?.number||'');
 const ranking=q?`<section class="ranking"><h2>${t(q.mode==='cooperative'?'team':'ranking')}</h2>${q.mode==='cooperative'?`<strong class="big-gain">${number(q.team.gain)}</strong>`:q.ranking.map((p,i)=>`<div class="rank ${p.id===party.you?'mine':''}"><span>${i&&q.ranking[i-1].gain===p.gain&&q.ranking[i-1].score===p.score?'=':i+1}</span><b>${esc(name(p.id))}</b><strong>${number(p.gain)}</strong><small>${p.score} ${t('point')}</small></div>`).join('')}</section>`:'';
 const won=quizWon(q,role,party?.you),winners=quizWinners(q);
 const avatar=id=>{const value=profile(id)?.avatar;return /^data:image\/(png|jpeg|webp);base64,/.test(value||'')?'<img class="winner-avatar" alt="" src="'+esc(value)+'">':'<span class="winner-avatar initial">'+esc(name(id).slice(0,1))+'</span>';};
 const finale=q?.ended?'<section class="finale" data-scene="'+esc(party.id)+':finale"><div class="trophy" aria-hidden="true">'+(q.winner?'🏆':'✦')+'</div><p class="eyebrow">'+t(q.mode==='cooperative'&&q.winner?'teamWon':won&&role==='controller'?'yourWin':winners.length>1?'winners':q.winner?'winner':'finished')+'</p><h1>'+esc(q.mode==='cooperative'?t('cooperative'):winners.length?winners.map(name).join(' · '):t('finished'))+'</h1><strong class="victory-gain">'+number(q.mode==='cooperative'?q.team.gain:q.ranking[0]?.gain)+'</strong><p>'+t('point')+'</p><div class="podium">'+(q.mode==='cooperative'?'':q.ranking.slice(0,3).map((p,i)=>'<div class="podium-place place-'+i+'" style="--delay:'+i*.2+'s">'+avatar(p.id)+'<b>'+esc(name(p.id))+'</b><span>'+number(p.gain)+'</span><div class="podium-step">'+(winners.includes(p.id)?'★':i+1)+'</div></div>').join(''))+'</div>'+(role==='controller'?'<button class="final replay" data-replay>'+t('again')+'</button>':'')+'</section>':'';
 const me=q?.you,can=online&&role==='controller'&&state.phase==='playing'&&q?.stage==='question'&&me&&!me.spectator&&me.answer===null;
 const question=q?`<div class="question-meta"><span>${t('question')} ${q.index+1} / ${q.total}</span><strong>${q.mode==='ranking'?((Number.isInteger(q.gain)?'':'≈ ')+'+'):''}${number(q.gain)}${q.mode==='ranking'?`<small class="gain-caption">${t('perCorrect')}</small>`:''}</strong><span class="clock ${q.left<=5&&q.stage==='question'?'urgent':''}" aria-label="seconds" aria-live="off">${q.left}s</span></div><div class="question-progress"><i style="width:${(q.index+1)/q.total*100}%"></i></div><div class="question-text">${esc(localized(q.question.prompt,state.language))}</div>${q.question.image?`<img class="question-image" src="${esc(q.question.image)}" alt="${t('question')} ${q.index+1}">`:''}<div class="answers">${q.question.answers.map((a,i)=>`<button type="button" data-answer="${i}" style="--delay:${i*.07}s" class="answer ${choice===i||me?.answer===i?'chosen':''} ${q.stage!=='question'&&q.question.correct===i?'correct':''} ${me?.hidden.includes(i)?'removed':''} ${q.stage==='reveal'&&me?.answer===i&&q.question.correct!==i?'incorrect':''}" ${!can||me?.hidden.includes(i)?'disabled':''}><b>${'ABCD'[i]}</b><span>${esc(localized(a,state.language))}</span></button>`).join('')}</div>${role==='controller'&&q.stage==='question'?`<div class="controls"><button class="fifty" data-fifty ${!can||me.used?'disabled':''}>${t('fifty')}</button><button class="final" data-confirm ${!can||choice===null?'disabled':''}>${me?.answer!==null&&me?t('locked'):t('confirm')}</button></div><p class="hint">${me?.spectator?t('spectator'):me&&!me.alive&&q.mode!=='ranking'?t('practice'):t('choose')}</p>`:''}${q.stage!=='question'?`<div class="reveal-ribbon" data-scene="${esc(key)}:reveal"><strong>${role==='controller'&&me?.answer!==q.question.correct?t('wrong'):t('bravo')}</strong><span>${t('next')}</span></div><p class="explanation">${t('correct')} : ${'ABCD'[q.question.correct]} · ${esc(localized(q.question.explanation,state.language))}</p>`:`<p class="hint">${q.answered} / ${q.participantCount} ${t('answers')}</p>`}`:'';
 patchView(document.querySelector('#app'),`<main class="show ${role}"><div class="spotlights" aria-hidden="true"></div><header><div class="wordmark">RETRO_MUSEUM <small>${t('title')}</small></div><button ${hostAudio?'hidden':''} class="sound" data-sound aria-label="${t('sound')}">${muted?'♪ ×':'♪'}</button></header>${q?.ended?finale:!q?`<section class="lobby"><div class="emblem">?</div><p class="eyebrow">1 → 1,000,000</p><h1>${t('waiting')}</h1><p>${t('lobby')}</p><strong>${party?.players.filter(p=>p.connected).length||0} players</strong></section>`:`<div class="show-heading"><h1>${esc(localized(q.title,state.language))}</h1><p>${t(q.mode==='ranking'?'rankingMode':q.mode)}</p></div><div class="play-grid"><section class="question-card" data-scene="${esc(key)}" aria-live="polite">${question}</section>${role==='display'||q.ended?ranking:`<aside class="personal-gain"><span>${esc(name(party.you))}</span><strong>${number(q.mode==='cooperative'?q.team.gain:me?.gain)}</strong></aside>`}</div>`}${state?.phase==='paused'||state?.phase==='intro'?`<div class="overlay"><div class="emblem">${state.phase==='intro'?Math.max(1,Math.ceil(state.introRemainingMs/1000)):'Ⅱ'}</div><h2>${t(state.phase==='intro'?'ready':'pause')}</h2></div>`:''}${q?.ended&&q.winner?celebration():''}</main>`);
}
document.addEventListener('click',async e=>{
 const button=e.target.closest('button');if(!button||button.disabled)return;
 if(hostAudio)parent.postMessage({retroMuseum:1,type:'audio-unlock'},'*');
 if(!hostAudio&&!audio){const Context=window.AudioContext||window.webkitAudioContext;if(Context)audio=new Context();}if(audio?.state==='suspended')await audio.resume().catch(()=>{});
 if(button.hasAttribute('data-sound')){muted=!muted;if(muted)stopAudio();render();return;}
 if(button.dataset.answer!==undefined){choice=Number(button.dataset.answer);render();return;}
 if(button.hasAttribute('data-confirm')){send('quizAnswer',{question:state.party.community.index,answer:choice});tone('quizQuestion');}
 if(button.hasAttribute('data-fifty'))send('quizFifty',{question:state.party.community.index});
 if(button.hasAttribute('data-replay'))send('playAgain');
});
addEventListener('message',e=>{if(e.source!==parent||e.data?.retroMuseum!==1)return;const m=e.data;if(m.type==='suspend'){choice=null;stopAudio();return;}if(m.type==='state'){state=m.state;role=m.role;online=m.online;hostAudio=m.hostAudio===true;try{render();}finally{parent.postMessage({retroMuseum:1,type:'rendered',renderId:m.renderId},'*');}}if(m.type==='error'){document.querySelector('.hint')?.replaceChildren(document.createTextNode(m.message||'Please try again.'));}});
addEventListener('pagehide',()=>stopAudio());
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAudio();});
parent.postMessage({retroMuseum:1,type:'ready',renderAck:true},'*');
